# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFurniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='Категория')),
                ('folder_name', models.CharField(max_length=50, verbose_name='Папка')),
            ],
        ),
        migrations.CreateModel(
            name='FurnitureProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furnproduct', models.CharField(max_length=100, verbose_name='Изделие')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.CategoryFurniture', verbose_name='Категория')),
            ],
            options={
                'ordering': ['furnproduct'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagepath', models.ImageField(upload_to='images', verbose_name='Изображение')),
                ('furnproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.FurnitureProduct', verbose_name='Изделие')),
            ],
        ),
    ]
